### ISSUE TITLE
mutagen-compose-beta.rb is not bumped to 0.13.1

### ISSUE THREAD

**Issue by rmachado-studocu** [havoc-io/homebrew-mutagen#3]
Hi folks!

I think you might missed the update to [mutagen-compose-beta.rb](https://github.com/mutagen-io/homebrew-mutagen/blob/master/Formula/mutagen-compose-beta.rb) 🤔  (to be 0.13.1)

Thank you for your time checking this! 👍 

Keep up the good work.

**Comment by xenoscopic** [comment]
Apologies!  Thank you @rmachado-studocu for catching that.
