### ISSUE TITLE
Provide older versions of mutagen-compose via brew.

### ISSUE THREAD

**Issue by trxg19** [havoc-io/homebrew-mutagen#4]
Hi, I need an older version of mutagen-compose. 
Unfortunately, I currently only receive the latest version (0.18.0) via. brew. Would it be possible for you to adapt the formula so that older versions such as mutagen are also available?

Thank you in advance!

**Comment by xenoscopic** [comment]
Yeah, I can do that, I'll set that up next week (I'm traveling this week).  We should test it with v0.17.6 anyway before we rely on it for v0.18.0, so now is a good time.  Thanks for asking.

**Comment by fsmeier** [comment]
+1 for that

**Comment by fsmeier** [comment]
I added a PR for the version 0.17

**Comment by az-joss** [comment]
+100
